# Generated by Django 2.2 on 2019-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
